EventEnum={
	EVENT_CLICK=1,
	EVENT_KEY_DOWN=2,
	EVENT_DIAMEND_CHNAGE=3,
	EVENT_CHIP_CHANGE=4,
	EVENT_HEARTBEAT_RSP=5,
    EVENT_BLACKJACK_VIEW_READY=6,
    EVENT_BLACKJACK_VIEW_CLOSE=7,
    EVENT_TIME_CLOCK=8,
    EVENT_TIME_3_CLOCK=9,
    EVENT_TIME_MINUTE=10,
    EVENT_NETWORK_DISCONNECT=11,
    EVENT_TIME_10_CLOCK=12,

    EVENT_MAINUI_SHOW_HIDE=13,

    EVENT_PROTO=14,

    EVENT_MATASES_VIEW_READY=20,
    EVENT_MATASES_TIME_OUT=21,
    EVENT_MATASES_ACTION=22,
    EVENT_CLICK_CLOCK=23,

    EVENT_ON_ACTIVE_VIEW_CLOSE=24,--活动界面关闭
    EVENT_LOADING_FINISH=25--加载完成
}